---
ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus
# public_network: "192.168.3.0/24"
public_network: "10.19.241.0/24"
# cluster_network: "192.168.4.0/24"
cluster_network: "10.19.241.0/24"
monitor_interface: eth1
devices:
  - '/dev/sda'
  - '/dev/sdb'
  - '/dev/sdc'
  - '/dev/sdd'
  - '/dev/sde'
